/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class OlmMessage {
  ciphertext: Buffer
  messageType: number
  constructor(messageType: number, ciphertext: Buffer)
}
