/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Account {
  constructor()
  get ed25519Key(): string
  get curve25519Key(): string
  get maxNumberOfOneTimeKeys(): number
  get oneTimeKeys(): string
  get fallbackKey(): string
}
export declare class InboundCreationResult { }
export declare class Session {
  get sessionId(): string
}
export declare class OlmMessage {
  ciphertext: string
  messageType: number
  constructor(messageType: number, ciphertext: string)
}
